### ISSUE TITLE
Missing videos in kinetics dataset

### ISSUE THREAD

**Issue by npmhung** [deepmind/tapnet#10]
Hello, 

Thank you for releasing these datasets.

I'm currently processing the dataset that you used to evaluate/train the model. However, when generating the pkl file for the kinetics dataset, I receive the following warning:

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/35062324/214989536-70415495-2d55-43c3-ac12-413015f5f98e.png">

Could you help to double check the dataset again if you have these videos?

FYI, I follow this link to download and extract the kinetics dataset: https://github.com/cvdfoundation/kinetics-dataset
When checking their annotation file: https://s3.amazonaws.com/kinetics/700_2020/annotations/val.csv, I could not find these videos either.

Best,
Hung

**Comment by cdoersch** [comment]
Greetins @npmhung ,

This is the unfortunate reality of Kinetics: most likely these videos have been removed from youtube and are no longer accessible.  I have seen the same warning using the source you mention.

Thankfully our benchmark is large enough that this should have a very small effect on your performance.  The numbers you get without them are valid to report.  Let us know if you have any other issues.
