### ISSUE TITLE
Question about the evaluation

### ISSUE THREAD

**Issue by qianduoduolr** [deepmind/tapnet#12]
Hi: 
   Thanks for your great job. I have a problem with the evaluation. 
   The paper proposes two different ways for evaluation (first or stride fashion). Using the first fashion for a point only in the first frame to be tracked, if the point is occluded at a certain timestamp t, and then appears again, is the predicted trajectory after t will be evaluated?

**Comment by serycjon** [comment]
yes, only the timestamps before the starting point are ignored ( https://github.com/deepmind/tapnet/blob/e8e85c7a55b91524984d54a6eaa2e855efcd7eeb/evaluation_datasets.py#L114 ). Note that the starting point is not always the first frame (frame number 0), but instead, it is the first frame where the given point was visible. E.g. some point is evaluated from frame 17 forward.

**Comment by qianduoduolr** [comment]
Thanks for your reply. 
In the situation we mentioned above, I wonder how TAPNet deals with the occlusions. I find the model leverages the Huber loss only at visible points.  When a point is occluded in the next frame and appears later, how the model performs point tracking?
