### ISSUE TITLE
How does model deal with the occlusions?

### ISSUE THREAD

**Issue by qianduoduolr** [deepmind/tapnet#13]
Hi !
I wonder how TAPNet deals with the occlusions. I find the model leverages the Huber loss only at visible points. For the evaluation of "first fashion", when a point is occluded in the next frame and appears later, how the model performs point tracking?  Does the model first detect the occlusion and then skip this frame, and track the point in the following frames?

**Comment by yangyi02** [comment]
Hi,

In short, current released TAPNet deals with occlusion and point tracking at each frame "independently".

TAPNet computes the cost volume between a query point and points at each frame individually. It predicts binary occlusion labels based on the cost volume. It also computes the most probable target point location based on the cost volume.

cost_volume = einshape('tbnhwd->t(bn)hwd', cost_volume)
occlusion = mods['hid1'](cost_volume)
...

TAPNet serves as a baseline for point tracking. There is no sequential tracking here. You can imagine all frame inference can be run in parallel.

Thanks.

**Comment by yangyi02** [comment]
Hi @qianduoduolr, does my reply address your question?
