### ISSUE TITLE
Kubric dataset: few occluded points are not labeled as occluded

### ISSUE THREAD

**Issue by ZHAOZHIHAO** [deepmind/tapnet#15]
Hi,

First, thanks for sharing your work.

In the Kubric dataset, I see that almost all occluded points are correctly labeled as occluded, but I still visually obverse few points among 1200=50 (videos) x 24 (points per video) are occluded. I'm sure these points are occluded because the foreground object has moved a large distance and the ground truth still stays the original position, like a position of the ground. I looked into the code, but still have not idea what caused this problem. Could you please give some suggestions or even a solution? Thanks.

There is also an issue that "reprojected position is off for points on objects" under the Kubric repository. Would you be willing to answer that too? https://github.com/google-research/kubric/issues/280

Best,
Zhihao

**Comment by ZHAOZHIHAO** [comment]
The following strategy seems removing bad ground-truth where occluded points are not labeled as occluded, though it will not preserve any occluded point anymore. For a 24-frame video, if a point is occluded in any frame, I mark it as occluded in the whole 24 frames. 

Best,
Zhihao

**Comment by cdoersch** [comment]
Closing this as it's redundant with https://github.com/google-research/kubric/issues/281 .  This is an issue with the Kubric code, not TAP-Vid.
