### ISSUE TITLE
Kubric evaluation set

### ISSUE THREAD

**Issue by npmhung** [deepmind/tapnet#16]
When evaluating the model on kubric, the generation code still randomly samples points from the kubric val videos each time. 

How do you make sure the sampled points are similar each time they are sampled?

**Comment by cdoersch** [comment]
We don't have plans to implement this.  In practice we find that the variance of the evaluation is quite low, as the number of points randomly sampled is very large (over 25000 points).  Furthermore, we're mostly interested in transfer performance on real data; the Kubric performance is mostly a diagnostic.  

That said, it shouldn't be terribly difficult to implement deterministic randomness using relevant tensorflow libraries.  We'd welcome pull requests in the Kubric repo.
