### ISSUE TITLE
Is there a demo or simple inference script for demo purposes?

### ISSUE THREAD

**Issue by arch-raven** [deepmind/tapnet#2]
I tried exploring the codebase but couldn't find a simple way to try out the model on a new video to evaluate performance? Did I miss the script (I am unfamiliar with JAX, coming from Pytorch ecosystem).

**Comment by cdoersch** [comment]
Currently no; adding a new dataset requires adding a reader to `evaluation_datasets.py`.  However, we've noted that this is a shortcoming of the current setup and will add one once the team has bandwidth.

**Comment by codylcs** [comment]
excellent work!!! but how far away from visual demo code release? thanks

**Comment by codylcs** [comment]
> Currently no; adding a new dataset requires adding a reader to `evaluation_datasets.py`. However, we've noted that this is a shortcoming of the current setup and will add one once the team has bandwidth.

hi,excellent work!!! but how far away from visual demo code release? thanks

**Comment by yangyi02** [comment]
We have added a preliminary inference code for a particular video (i.e. horsejump-high.mp4), please check latest README.md. 

In short, you can try using the command:

python3 ./tapnet/experiment.py \
  --config=./tapnet/configs/tapnet_config.py \
  --jaxline_mode=eval_inference \
  --config.checkpoint_dir=./tapnet/checkpoint/ \
  --config.experiment_kwargs.config.input_video_path=horsejump-high.mp4 \
  --config.experiment_kwargs.config.output_video_path=result.mp4

The inference only serves as an example. It will resize the video to 256x256 resolution, sample 20 random query points on the first frame and track these random points in the rest frames.
