### ISSUE TITLE
Code and checkpoint for Kubric-VFS-Like baseline

### ISSUE THREAD

**Issue by ayshrv** [deepmind/tapnet#20]
Hi all,

I have been working on evaluating the Kubric-VFS-like baseline on the Kubric dataset. Would it be possible for you to provide the evaluation code for Kubric-VFS-Like baseline and the checkpoint used to get those results? And for evaluating on Kubric, was the Kubric-VFS-like baseline also trained on Kubric?  

Also, it would be great if you could provide the evaluation code and checkpoint for RAFT as well.

Thanks!

**Comment by cdoersch** [comment]
Some reference code for the kubric-vfs-like baseline is included in this codebase, although admittedly it isn't very well tested.  We don't really plan to maintain it as we believe TAP-Net made this code obsolete.  If you change prediction_algo from 'cost_volume_regressor' to 'cost_volume_cycle_consistency' and re-train, the result should approximate the Kubric-VFS-Like from the Kubric paper.

RAFT used code we borrowed from another team, so we will be unable to release this.  Sorry about that.  However, I believe others have implemented RAFT baselines in public repositories, including TAP-Vid evaluations.  See the discussion here: https://github.com/deepmind/tapnet/issues/17

**Comment by ayshrv** [comment]
Thanks for the info. That is helpful!
