### ISSUE TITLE
jax requires jaxlib

### ISSUE THREAD

**Issue by havok2-htwo** [deepmind/tapnet#25]
I tried to install this under windows, but there is no win version of jax. Is it possible to run this under windows?

**Comment by dilaragokay** [comment]
Hi @havok2-htwo,

Unfortunately, we have not tried running the TAP models in this repository on Windows. But [this document](https://jax.readthedocs.io/en/latest/developer.html) shows how to install JAX with a section dedicated to [Windows-specific steps](https://jax.readthedocs.io/en/latest/developer.html#additional-notes-for-building-jaxlib-from-source-on-windows). 

Hope that helps, and let us know if you face any other issues!

**Comment by VincentSimonin** [comment]
I have a successful install on Windows by installing a wheel from here: [](https://github.com/cloudhan/jax-windows-builder)
List of available wheels: [](https://whls.blob.core.windows.net/unstable/index.html)

In my case:

> pip install jaxlib-0.4.11-cp38-cp38-win_amd64.whl

Hope that helps!

**Comment by vitacon** [comment]
> I have a successful install on Windows

Would you mind sharing your `conda list`?
I installed `jax` but now I get other error messages related to `tensorflow` so I suspect I need a different version of it.
