### ISSUE TITLE
About the evaluation on Kinetics

### ISSUE THREAD

**Issue by qianduoduolr** [deepmind/tapnet#28]
Hi, thanks for your excellent work!
I have a problem with the evaluation on TAP-Vid-Kinetics.
I found three files in TAP-Vid-Kinetics, including "train.txt", "test.txt", and "val.txt". Are all used for evaluation? Or just the videos in the test set are used?

**Comment by cdoersch** [comment]
For the numbers we compute in TAP-Vid and TAPIR, we evaluate on all videos, and this is what we intend people to do with our dataset.  These txt files are ignored.

Reviewers for the TAP-Vid paper requested that we create split files in case others have a use for them, but we aren't currently using them in any way.

**Comment by qianduoduolr** [comment]
Ok, thanks.
