### ISSUE TITLE
Comparison between TAP-Net and PIPs

### ISSUE THREAD

**Issue by amitabe** [deepmind/tapnet#3]
Hi,

You only mention that PIPs is a concurrent work to TAP-Vid/Net.

Are you planning to show any comparisons between these 2 works?

**Comment by yangyi02** [comment]
We are working on it. Thanks for your patience.

**Comment by HarryHsing** [comment]
> We are working on it. Thanks for your patience.

Hi, I hope this message finds you well. I was wondering if any progress has been made on this matter. Thank you!

**Comment by cdoersch** [comment]
The numbers have been added to the most recent version of our arxiv paper

**Comment by HarryHsing** [comment]
> The numbers have been added to the most recent version of our arxiv paper

Thank you very much for the update! Will you release the evaluation code of PIPs on Kinetics, Kubric, DAVIS, and RGB-Stacking? I am really looking forward to it, thank you!

**Comment by m43** [comment]
I've got PIPS results that are close to the ones
reported in the updated arxiv paper using this
somewhat refactored [fork](https://github.com/m43/pips/tree/evaluate-on-tapvid) of PIPs.

My numbers are in the last two rows:
![image](https://user-images.githubusercontent.com/17498813/230939960-4be52065-0821-4826-bc20-24f600764152.png)

However, my RAFT numbers do not match the
reported ones, except on the DAVIS subset.

If interested, here are some entry points:
1. [Batched PIPS forward pass for chained trajectory prediction](https://github.com/m43/pips/blob/a984b1e9bb9cc5c3d1647073f71da73460102d2f/evaluation_model/pips.py#L162)
2. [Evaluation for loop](https://github.com/m43/pips/blob/a984b1e9bb9cc5c3d1647073f71da73460102d2f/evaluate.py#L124-L172)
3. [Documentation on running the evaluation](https://github.com/m43/pips/blob/a984b1e9bb9cc5c3d1647073f71da73460102d2f/docs/evaluate_on_tapvid.md#evaluate-models-on-tap-vid)
4. [PIPs environment setup](https://github.com/m43/pips/blob/a984b1e9bb9cc5c3d1647073f71da73460102d2f/docs/reproduction.md#environment-setup)

**Comment by HarryHsing** [comment]
> fork

Really appreciate it! Thanks!

**Comment by HarryHsing** [comment]
> I've got PIPS results that are close to the ones reported in the updated arxiv paper using this somewhat refactored [fork](https://github.com/m43/pips/tree/evaluate-on-tapvid) of PIPs.
> 
> My numbers are in the last two rows: ![image](https://user-images.githubusercontent.com/17498813/230939960-4be52065-0821-4826-bc20-24f600764152.png)
> 
> However, my RAFT numbers do not match the reported ones, except on the DAVIS subset.
> 
> If interested, here are some entry points:
> 
> 1. [Batched PIPS forward pass for chained trajectory prediction](https://github.com/m43/pips/blob/a984b1e9bb9cc5c3d1647073f71da73460102d2f/evaluation_model/pips.py#L162)
> 2. [Evaluation for loop](https://github.com/m43/pips/blob/a984b1e9bb9cc5c3d1647073f71da73460102d2f/evaluate.py#L124-L172)
> 3. [Documentation on running the evaluation](https://github.com/m43/pips/blob/a984b1e9bb9cc5c3d1647073f71da73460102d2f/docs/evaluate_on_tapvid.md#evaluate-models-on-tap-vid)
> 4. [PIPs environment setup](https://github.com/m43/pips/blob/a984b1e9bb9cc5c3d1647073f71da73460102d2f/docs/reproduction.md#environment-setup)


fork

Really appreciate it! Thanks!
