### ISSUE TITLE
Inference with GPU failed

### ISSUE THREAD

**Issue by 4BD0U** [deepmind/tapnet#33]
Hello,
I'm having trouble launching my model with my GPU. Here are the logs I see in the terminal:
"""
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
"""
However, when I check if TensorFlow is able to load the GPU using this command:
"""
gpu_devices = tf.config.list_physical_devices('GPU')
"""
I get the following result:
"""
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
"""
Could someone please help me resolve this issue?

**Comment by dilaragokay** [comment]
Have you installed JAX with GPU support as described [here](https://github.com/google/jax#installation)?

**Comment by 4BD0U** [comment]
Thank you for your response, that was correct, but after installation, I still can't get it to run on my GPU. I only have 10GB of VRAM. Does anyone have an idea about the amount of VRAM I need to run the model?

**Comment by cdoersch** [comment]
The live demo can be run with 1GB of vram, so that's unlikely to be the issue.  You need a version of JAX's cuda library that's compatible with both the cuda and cudnn that you have installed.  Are you able to run other JAX demos on GPU, or is this a tapnet-specific issue?

**Comment by 4BD0U** [comment]
Thank you for your feedback. No, this is the first time I'm using JAX with my GPU. For testing, I'm using a 30-second video with 5 frames per second. When I run the test and monitor my VRAM using nvidia-smi, I noticed that before encountering the error, my VRAM usage goes up to 10 GB, and then it crashes.

The error I'm getting is:
<<< The CUDA linking API did not work. Please use XLA_FLAGS=--xla_gpu_force_compilation_parallelism=1 to bypass it, but expect to get longer compilation time due to the lack of multi-threading. Original error: INTERNAL: nvlink exited with non-zero error code 256, output: nvlink fatal>>>

**Comment by cdoersch** [comment]
Your benchmarks are likely dominated by compilation time.  See this thread: https://github.com/deepmind/tapnet/issues/26

**Comment by 4BD0U** [comment]
Thank you so much for your help.
