### ISSUE TITLE
Incorrect evaluation in the 'first' mode?

### ISSUE THREAD

**Issue by serycjon** [deepmind/tapnet#34]
Hi,

I wonder about the code [here](https://github.com/deepmind/tapnet/blob/ba1a8c8f2576d81f7b8d69dbee1e58e8b7d321e1/evaluation_datasets.py#L117C3-L119C43)

It seems to me that it is supposed to turn off evaluation of points before the query frame.
I however don't understand why / how is the 'index' computed. We already have the query frames computed [here](https://github.com/deepmind/tapnet/blob/ba1a8c8f2576d81f7b8d69dbee1e58e8b7d321e1/evaluation_datasets.py#L111), so why the np.where?

Anyways, I thing that the code is incorrect. The [for loop](https://github.com/deepmind/tapnet/blob/ba1a8c8f2576d81f7b8d69dbee1e58e8b7d321e1/evaluation_datasets.py#L117C1-L117C42) loops over the "batch" dimension, which is [always 1](https://github.com/deepmind/tapnet/blob/ba1a8c8f2576d81f7b8d69dbee1e58e8b7d321e1/evaluation_datasets.py#L327C1-L330C52). This means that the current code does not turn off the evaluation before the query point.

I think it should be corrected to:
```python
for i in range(gt_occluded.shape[1]): # loop over the query points
  index = np.where(gt_occluded[0, i] == 0)[0][0]  # find the first unoccluded frame for that query point (in singleton batch 0)
  evaluation_points[i, :index] = False
```

or equivalently:
```python
N_queries = gt_occluded.shape[1]
for i in range(N_queries):
  evaluation_points[i, :query_frame[i]] = False
```

Am I missing something? Or can I make a pull request for this correction?

BTW it would be very nice if you could provide the raw results (i.e., the `pred_occluded` and `pred_tracks` arguments of `compute_tapvid_metrics`) of the trackers evaluated in your papers, so that people could evaluate the trackers on different metrics without having to re-implement and without wasting quite a lot of compute (pretty please?)

Best regards!

**Comment by serycjon** [comment]
Thanks for looking into this.

> It should have a very minor effect on the numbers (it only affects points which aren't visible on the first frame, which is quite rare in TAP-Vid).

Agree. (maybe some problems on kinetics, in the videos containing cuts? Haven't checked how often is the query frame not the first one)

> I actually think I'm going to use a fix that completely removes the loop though (should be faster).

In my experience this is not a speed bottleneck and I would expect the overall speed gains for the tracking/evaluation pipeline be completely insignificant. I strongly prefer simple/obvious readable code in metrics computation to stay on the safe side and not make unnecessary mistakes.

> Something like this: ...
> We'll test this shortly, but does this look reasonable to you?

I am sorry I don't have time to check it properly at the moment (+ leaving for vacations for some time). But seems ok on first (slow) glance.

> I'll discuss whether we can release our raw predictions with the team.

Thanks a lot.

**Comment by m43** [comment]
Hej, the snippet is correct, just a `.astype(bool)` is missing to convert the `evaluation_points` to a boolean array to use the `&` operator later. Do you think the change should be merged? I understand that some of the reported numbers might change, for example on Kinetics, but also on other datasets such as the new [PointOdyssey](https://github.com/y-zheng18/point_odyssey). The bug has propagated to related works such as [CoTracker](https://github.com/facebookresearch/co-tracker/blob/884e13f4ad4313e65b319966395d2859e7d9aa0d/cotracker/evaluation/core/eval_utils.py#L68-L73).

**Comment by cdoersch** [comment]
The change has already been merged; I'm hoping that related works picked up on it.  If you find repos where it's wrong, please raise an issue and point back to this thread.

I think the issue you mentioned is corrected in the checked-in version: https://github.com/deepmind/tapnet/blob/main/evaluation_datasets.py#L117

**Comment by cdoersch** [comment]
Fix is in this commit: https://github.com/deepmind/tapnet/commit/3c127551a880808cbcbe98c03323935cdf2174c3

**Comment by m43** [comment]
You're right, it had been merged. Thanks!
