### ISSUE TITLE
Cpu Inference Problems on live_demo

### ISSUE THREAD

**Issue by ibtehajali67** [deepmind/tapnet#36]
I am getting inference for live video on  CPU,Speed is very low , I thing it is because of cpu but my problem is that to increase  number of frame in video. Do you have idea about it. 
In Simple word, want to increase speed on cpu

Thanks in advance

**Comment by cdoersch** [comment]
TAPIR is a complex neural network with millions of parameters; it is designed for use on a GPU and making it run fast on CPU is an open research problem.  Sorry I can't be more helpful.
