### ISSUE TITLE
Run TAPIR Inference without resizing the video

### ISSUE THREAD

**Issue by vrk7** [deepmind/tapnet#39]
Hi tEAM,

Can the inference be done without resizing the video frames?

**Comment by cdoersch** [comment]
Yes, TAPIR can be run on any resolution; internally it will perform its initialization on 256x256 and then refine on progressively higher resolution.  It should work out-of-the-box in our colab demo.

**Comment by vrk7** [comment]
My issue is, i have annotation of segments in COCO format. When i converted this into 2D points, should I have the points according to the original frame or reduced frame?

**Comment by cdoersch** [comment]
They should be scaled relative to the size of the video that you input into TAPIR.  I.e. if its 512x512, your points should be in the range [0,512].
