### ISSUE TITLE
Training with CUDA

### ISSUE THREAD

**Issue by HarryHsing** [deepmind/tapnet#4]
Hi, I have already installed JAX version with CUDA. 
However, it seems when I run `python ./experiment.py --config ./configs/tapnet_config.py`, 
it is still trying to use the TPU and eventually fails cause I don't have access to it. And then, end up using CPU by default.

I wonder how to use the CUDA to train and evaluate the model.

Thank you very much for your support in advance!

**Comment by cdoersch** [comment]
This sounds like an issue with your jax installation.  You need to make sure you install a version of jax that's compatible with your cuda and cudnn installations.  For our tests, we used CUDA 11.4 and cudnn 8.2.4 on ubuntu 20.04 and then installed jax via:

```
pip install --upgrade jax jaxlib==0.3.15+cuda11.cudnn82 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```
