### ISSUE TITLE
Nearly 0% GPU utilization for a large majority of time during inference

### ISSUE THREAD

**Issue by hasnainv** [deepmind/tapnet#42]
I am running inference on a sequence of a video of shape (400,256,256,3) and trying to track 2000 points in that video using the offline model. 
Unfortunately, the inference is very slow and the GPU util is 0% most of the time. 
Do you know what could be going on and how we could get better GPU util?

![image](https://github.com/deepmind/tapnet/assets/979383/8f68c4f1-460b-4b2d-ae5d-3e270fea64ec)

**Comment by hasnainv** [comment]
JAX also prints out this in the command line. 

![image (1)](https://github.com/deepmind/tapnet/assets/979383/430ee4c1-98a5-409d-ab28-4cfcedd611f3)

**Comment by cdoersch** [comment]
You're seeing compile time, not runtime.  Every time the size of the input tensors changes (different resolution, different number of frames, different number of query points), the entire inference graph needs to be recompiled, which takes on the order of minutes.

The solution is typically to make sure you're always running with the same size input.  You can pad the query points with zeros if necessary without changing the output for the other points.

**Comment by hasnainv** [comment]
Thanks @cdoersch , that's correct. Most of the that was recompilation time. I'm now padding my data and keeping the dimensions same for every run.
