### ISSUE TITLE
how to set a specific gpu to use in tapir code

### ISSUE THREAD

**Issue by CHYjeremy** [deepmind/tapnet#43]
Hi authors,

suppose that i have successfully installed compatible version of jax w.r.t to cuda/cudnn, how do i modify the following code so that i could:

1. select a certain gpu to use i.e. cuda:1
2. check that i am indeed using an gpu
3. avoid every-time compilation(after i set the input tensor size fixed)

ps: i am running inference on videos in a dataset by the following for loop code (it is the colab format):
      
      def inference():
          ...
          ...

      model = hk.transform_with_state(build_model)
      model_apply = jax.jit(model.apply)
      
      ### for loop every video in a dataset
      for i in os.listdir("/home/chy/dataset"):
          if not i.startswith("."):
      
              rh,rw = 256,256
              video = np.load("/home/chy/dataset/"+i)
              height, width = video.shape[1:3]
              frames = media.resize_video(video, (rh, rw))
              query_points = points

              tracks, visibles = inference(frames, query_points)
              tracks = transforms.convert_grid_coordinates(tracks, (rw, rh), (width, height))
              np.save("path",tracks)

much thx~

**Comment by m43** [comment]
To select a specific GPU, you can specify the device when using `jax.jit`. Here's an example:

```python
gpus = jax.devices('gpu')
device = gpus[1] # If you want to use "cuda:1"
model_apply = jax.jit(model.apply, device=device)
```

To confirm that you are utilizing the GPU, execute `nvidia-smi` in the terminal. It will display GPU usage statistics and the associated processes. For a real-time monitoring tool, consider using `nvtop` which provides a "top-like" interface.

As for avoiding recompilation, [JAX compiles the function](https://jax.readthedocs.io/en/latest/jax-101/02-jitting.html#jit-compiling-a-function) and caches the XLA code when a `jax.jit` function is called for the first time. Subsequent calls use the cached version unless there are changes in arguments labeled as `static` in the call to [`jax.jit`](https://jax.readthedocs.io/en/latest/_autosummary/jax.jit.html).

Lastly, to prevent JAX from [preallocating substantial GPU memory](https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html), consider setting this environment variable:

```bash
export XLA_PYTHON_CLIENT_PREALLOCATE=false
```

Hope this helps!

**Comment by CHYjeremy** [comment]
Thanks for your amazing answer!

**Comment by CHYjeremy** [comment]
Thank you very much for the amazing answer.

but let me follow up with your suggestion on setting environment variable, may i ask, to what extent will it hurt the performance(speed) of the algorithm when you prevent jax from preallocating much gpu memory? 

thanks.

**Comment by m43** [comment]
Allocating memory on-the-fly might not have a significant impact on speed compared to preallocating, though this isn't explicitly detailed in the documentation. Disabling preallocation can reduce overall memory usage, especially if JAX doesn't fully utilize the preallocated memory. This becomes particularly relevant if TensorFlow or PyTorch models run concurrently on the same GPU. However, without preallocation, there's an increased risk of memory fragmentation, which could lead to OOM issues for JAX programs that need to consume most of the GPU memory. You can find more details on this topic [here](https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html). If you're not facing any OOM issues, the default memory settings might be well-suited for your needs.

**Comment by CHYjeremy** [comment]
thank you very much @m43
