### ISSUE TITLE
tapir give out negative corrdinate

### ISSUE THREAD

**Issue by CHYjeremy** [deepmind/tapnet#46]
Hi authors,

i find that tapir is sometimes giving negative coordinate, why do it happen and what do you think that it represent?

thx!

**Comment by cdoersch** [comment]
Remember that TAPIR is trained on synthetic data.  There is nothing in the architecture which constrains the model outputs to be inside the bounds of the image.  Out-of-domain data might cause some amount of noise in the predictions; if this happens near the image boundries, then the predictions will be outside of the bounds of the image.

How far outside of the image are the values?  If they're close, then you should probably just clip them to be within the image boundary.

**Comment by CHYjeremy** [comment]
Got it! @cdoersch. Thanks a lot for your explanation! No, it is not way too far away from the boundary.
