### ISSUE TITLE
Animating still images with TAPIR

### ISSUE THREAD

**Issue by ernestchu** [deepmind/tapnet#52]
Hi, thanks for your great works on TAP-Net and TAPIR.

I'm interested in Section 7 of TAPIR paper. Where can I find some demo videos or related source code? Thanks!

**Comment by cdoersch** [comment]
Sorry, we don't plan to release the source code or models for the "animating still images" application.

**Comment by ernestchu** [comment]
Okay. Thanks anyway. Any chance we got to see some demo videos?
