### ISSUE TITLE
eval results seems not so good?

### ISSUE THREAD

**Issue by codylcs** [deepmind/tapnet#7]
note:this is not a bug event
when i run scripts as flow:
`python3 ./tapnet/experiment.py \
  --config=./tapnet/configs/tapnet_config.py \
  --jaxline_mode=eval_davis_points \
  --config.checkpoint_dir=./tapnet/checkpoint/ \
  --config.experiment_kwargs.config.davis_points_path=/path/to/tapvid_davis.pkl`
i got result in \tapnet\checkpoint\eval_davis_points\100000,there are 0.mp4 - 9.mp4 generated; in every mp4 video,there are four frames in parent PIC,though all frames seems blur; the points in pics all seems bad, is it a real result, i mean ,why results not seems amazing instead of disappointing?

**Comment by codylcs** [comment]
results looks as flowing
![image](https://user-images.githubusercontent.com/48380363/208817775-71ddaa73-4f2a-4b1a-8f51-ac72ea50b3df.png)

**Comment by codylcs** [comment]
![image](https://user-images.githubusercontent.com/48380363/208822055-186b09c1-f153-4d85-9695-cc946ec080df.png)

**Comment by yangyi02** [comment]
Hi thanks for your observation.

Our current checkpoint serves as a simple baseline and is not as amazing as you expected. 

We are working on improving the model while also hoping our dataset can serve as a benchmark for others (i.e. pips) to continue improving point tracking.

Thanks for your attention.
